grafana:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.vitalsoftai.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.vitalsoftai.com
  grafana.ini:
    server:
      root_url: "https://grafana.vitalsoftai.com"